name: vault
size: 1
# hostname: # required

image: vault:1.4.2
bankVaultsImage: banzaicloud/bank-vaults:1.1.0

dynamodb:
  table: vault
  region: eu-west-1

serviceMonitor:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-public
    kubernetes.io/tls-acme: "true"